### ISSUE TITLE
New feature : attach files from page resources or with the send message form

### ISSUE THREAD

**Issue by Oktopuce** [fabarea/messenger#28]
When you send a Newsletter, it's very useful to attach some files to it.

It's available with your extension but only using the API, I think a very interesting feature could be to add the opportunity to attach file from page Resources or with the send message form.

Attach a file from Page Resources is very easy,  I've already done it extending your extension, have a look in files attached.

[BackendMessageController.zip](https://github.com/fabarea/messenger/files/3771178/BackendMessageController.zip)

Florian

**Comment by Oktopuce** [comment]
Another solution could be to add a **signal/slot** or a **hook** in **BackendMessageController::enqueueAction()** to add the possibility to attach files.

**Comment by fabarea** [comment]
Sorry, for the late, late, late, late answer. I **guess** you found another solution in the meanwhile. 
We are reactivating the dev of the extension in case.
